# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tenderly < Formula
  desc "Tenderly helps you observe your contracts in any environment."
  homepage "https://github.com/Tenderly/tenderly-cli"
  version "1.7.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Tenderly/tenderly-cli/releases/download/v1.7.0/tenderly_1.7.0_Darwin_arm64.tar.gz"
      sha256 "e52768a398f780c3143e5f8a26445414cc022d92cc69b85681e2703b87703a09"

      def install
        bin.install "tenderly"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Tenderly/tenderly-cli/releases/download/v1.7.0/tenderly_1.7.0_Darwin_amd64.tar.gz"
      sha256 "4733ad7ff731a9568ec4eed356b6a0a1bd71262b36b3f75d1953d4314f6216a6"

      def install
        bin.install "tenderly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tenderly/tenderly-cli/releases/download/v1.7.0/tenderly_1.7.0_Linux_arm64.tar.gz"
      sha256 "c27bd493c7104cba872f25e0463197a2bce76c23ef6b179f634ff536d3f5e7be"

      def install
        bin.install "tenderly"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Tenderly/tenderly-cli/releases/download/v1.7.0/tenderly_1.7.0_Linux_amd64.tar.gz"
      sha256 "97983f30571d9409657bed876614be7cc8deaccf11d63f58413b1edf2732eb40"

      def install
        bin.install "tenderly"
      end
    end
  end
end
